// GENERATED by scripts/import-backgrounds.mjs - do not edit.
export const BG_LAYERS = ["sky","far","mid","ground","foreground"] as const;
export const BG_PARALLAX: Record<string, number> = {"sky":0,"far":0.12,"mid":0.28,"ground":0,"foreground":0.5};
export const BG_COMBAT_SCENES = ["swamp_normal","swamp_boss","peaks_normal","peaks_boss","canyon_normal","canyon_boss","caverns_normal","caverns_boss","storm_normal","storm_boss","dungeon_a_normal","dungeon_a_boss","dungeon_s_normal","dungeon_s_boss","dungeon_ss_normal","dungeon_ss_boss","dungeon_ssr_normal","dungeon_ssr_boss"] as const;
export const BG_SCREEN_SCENES = ["menu","gacha","collection","market","forge","lobby"] as const;
// Dungeon rank -> scene ids (normal / boss room).
export const BG_DUNGEON: Record<string, { normal: string; boss: string }> = {"f":{"normal":"swamp_normal","boss":"swamp_boss"},"e":{"normal":"peaks_normal","boss":"peaks_boss"},"d":{"normal":"canyon_normal","boss":"canyon_boss"},"c":{"normal":"caverns_normal","boss":"caverns_boss"},"b":{"normal":"storm_normal","boss":"storm_boss"},"a":{"normal":"dungeon_a_normal","boss":"dungeon_a_boss"},"s":{"normal":"dungeon_s_normal","boss":"dungeon_s_boss"},"ss":{"normal":"dungeon_ss_normal","boss":"dungeon_ss_boss"},"ssr":{"normal":"dungeon_ssr_normal","boss":"dungeon_ssr_boss"}};
