// Importer: painted enemy sheets (phase_2_enemies) -> public/art/enemies/*.webp
// + src/lib/art/enemies.generated.ts (frames/fps/loop per animation). Usage:
//   node scripts/import-enemies.mjs "<downloads dir>"
import sharp from "sharp";
import { mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { finder, readJson } from "./lib/art-sources.mjs";

const base = process.argv[2];
if (!base) throw new Error("pass the downloads directory");
const find = finder(base, "enemies");
const csv = find("animations.csv");
const catalog = readJson(find("boss_catalog.json"));

const FRAME = { 768: 384, 1024: 384 }; // delivered cell -> output cell (px)
const out = join("public", "art", "enemies");
mkdirSync(out, { recursive: true });

const rows = readFileSync(csv, "utf8").replace(/^﻿/, "").trim().split(/\r?\n/);
const head = rows.shift().split(",");
const anims = {}; // "<enemy_id>_<element>_<action>" -> meta
let bytes = 0;
for (const line of rows) {
  // fields with quotes ("[384, 720]") contain commas
  const cols = line.match(/("[^"]*"|[^,]*)(,|$)/g).map((c) => c.replace(/,$/, "").replace(/^"|"$/g, ""));
  const r = Object.fromEntries(head.map((h, i) => [h, cols[i]]));
  const src = find(r.file);
  if (!src) throw new Error(`missing ${r.file}`);
  const cell = JSON.parse(r.frame_size)[0];
  const to = FRAME[cell];
  const frames = Number(r.frames);
  const name = r.file.replace(/^enemies\//, "").replace(".png", "");
  const buf = await sharp(src)
    .resize(to * frames, to, { kernel: "lanczos3" })
    .webp({ quality: 82, alphaQuality: 90, effort: 5 })
    .toBuffer();
  bytes += buf.length;
  await sharp(buf).toFile(join(out, `${name}.webp`));
  anims[name] = { frames, fps: Number(r.fps), loop: r.loop === "True", cell: to };
}

const bossByRank = Object.fromEntries(catalog.bosses.map((b) => [b.rank, `boss_${b.id}`]));
writeFileSync(
  join("src", "lib", "art", "enemies.generated.ts"),
  `// GENERATED by scripts/import-enemies.mjs - do not edit.\n` +
    `export type EnemyAnimMeta = { frames: number; fps: number; loop: boolean; cell: number };\n` +
    `export const ENEMY_ANIMS: Record<string, EnemyAnimMeta> = ${JSON.stringify(anims, null, 1)};\n` +
    `// Final boss design per dungeon rank (boss_catalog.json).\n` +
    `export const FINAL_BOSS_BY_RANK: Record<string, string> = ${JSON.stringify(bossByRank, null, 1)};\n`,
);
console.log(Object.keys(anims).length, "sheets", (bytes / 1e6).toFixed(1), "MB");
