// Importer: painted effects (phase_2_effects) -> public/art/effects/*.webp (+ reduced/)
// + src/lib/art/effects.generated.ts (frames/fps/loop/finish/cell/rows). Usage:
//   node scripts/import-effects.mjs "<downloads dir>"
import sharp from "sharp";
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { finder, readJson } from "./lib/art-sources.mjs";

const base = process.argv[2];
if (!base) throw new Error("pass the downloads directory");
const find = finder(base, "effects");
const catalog = readJson(find("effect_catalog.json"));

const out = join("public", "art", "effects");
mkdirSync(join(out, "reduced"), { recursive: true });

// Big cells are scaled down (<= 768 wide, <= 512 tall); small ones stay native.
const scaleOf = ([w, h]) => Math.min(1, 768 / w, 512 / h);
let bytes = 0;
const meta = {};
for (const e of catalog.effects) {
  const k = scaleOf(e.frame_size);
  const cell = e.frame_size.map((v) => Math.round(v * k));
  const { columns, rows } = e.layout;
  const id = e.id.replace(/^vfx_/, "");
  for (const [rel, dir, cols] of [
    [e.file, "", columns],
    [e.reduced, "reduced", 1],
  ]) {
    const src = find(rel);
    if (!src) throw new Error(`missing ${rel}`);
    const buf = await sharp(src)
      .resize(cell[0] * cols, cell[1] * rows, { kernel: "lanczos3" })
      .webp({ quality: 85, alphaQuality: 90, effort: 5 })
      .toBuffer();
    bytes += buf.length;
    await sharp(buf).toFile(join(out, dir, `${id}.webp`));
  }
  meta[id] = {
    frames: e.frames,
    fps: e.fps,
    loop: e.loop,
    finish: e.finish,
    cell,
    rows,
    ...(e.glyph_row ? { glyphRow: e.glyph_row, advance: Math.round(e.advance_px * k) } : {}),
  };
}

writeFileSync(
  join("src", "lib", "art", "effects.generated.ts"),
  `// GENERATED by scripts/import-effects.mjs - do not edit.\n` +
    `export type EffectMeta = {\n  frames: number;\n  fps: number;\n  loop: boolean;\n  finish: string; // remove | hold | loop\n  cell: [number, number]; // output px of one cell\n  rows: number;\n  glyphRow?: Record<string, number>;\n  advance?: number;\n};\n` +
    `export const EFFECTS: Record<string, EffectMeta> = ${JSON.stringify(meta, null, 1)};\n`,
);
console.log(Object.keys(meta).length, "effects", (bytes / 1e6).toFixed(1), "MB");
