// Importer: painted heroes + hand weapons (PNG @1x, 768px frames) -> public/art/{heroes,weapons} WebP (256px frames)
// and src/lib/art/heroes.ts (metadata). Usage: node scripts/import-heroes.mjs "<downloads dir>"
import sharp from "sharp";
import { readdirSync, mkdirSync, existsSync, statSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const base = process.argv[2];
if (!base) throw new Error("pass the downloads directory");
const FRAME = 256;

// Every art/ folder the Drive download was split into.
const roots = readdirSync(base)
  .filter((d) => d.startsWith("Proyecto de Juego") && statSync(join(base, d)).isDirectory())
  .map((d) => join(base, d, "art"));
const find = (lot, sub, pred) => {
  const out = new Map();
  for (const r of roots) {
    const dir = join(r, `phase_2_${lot}`, sub);
    if (!existsSync(dir)) continue;
    for (const f of readdirSync(dir)) if (f.endsWith(".png") && !f.includes("_2x") && pred(f) && !out.has(f)) out.set(f, join(dir, f));
  }
  return out;
};
const first = (lot, file) => roots.map((r) => join(r, `phase_2_${lot}`, file)).find(existsSync);

async function convert(src, dest, scaleDown) {
  const img = sharp(src);
  const { width, height } = await img.metadata();
  await img.resize(Math.round(width / scaleDown), Math.round(height / scaleDown), { kernel: "lanczos3" })
    .webp({ quality: 82, alphaQuality: 90, effort: 5 }).toFile(dest);
}

mkdirSync("public/art/heroes/acc", { recursive: true });
mkdirSync("public/art/weapons", { recursive: true });

const heroes = find("heroes", "heroes", (f) => /^hero_[a-z]+_[a-z]+_[a-z_0-9]+\.png$/.test(f) && !f.includes("_trait_"));
const accs = find("heroes", "accessory_layers", () => true);
const icons = find("weapons", "icons", (f) => f.startsWith("icon_weapon_"));
for (const [f, p] of heroes) await convert(p, join("public/art/heroes", f.replace(".png", ".webp")), 3);
for (const [f, p] of accs) await convert(p, join("public/art/heroes/acc", f.replace("hero_", "").replace("_trait", "").replace(".png", ".webp")), 3);
for (const [f, p] of icons) await convert(p, join("public/art/weapons", f.replace(".png", ".webp")), 2);
console.log({ heroes: heroes.size, accessories: accs.size, weaponIcons: icons.size });

// Metadata from animations.csv (frames/fps/finish per action) and trait_catalog.json.
const csv = readFileSync(first("heroes", "animations.csv"), "utf8").trim().split("\n").slice(1).map((l) => l.trim().split(","));
const actions = {};
for (const [, , , action, frames, fps, finish] of csv) actions[action] = { frames: +frames, fps: +fps, loop: finish === "loop", hold: finish === "hold_last" };
const cat = JSON.parse(readFileSync(first("heroes", "trait_catalog.json"), "utf8"));
const traits = Object.fromEntries(cat.traits.map((t) => [t.game_id, t.asset_id]));
const accKeys = [...accs.keys()].map((f) => f.replace("hero_", "").replace("_trait", "").replace(".png", ""));
writeFileSync("src/lib/art/heroes.ts", `// GENERATED by scripts/import-heroes.mjs - do not edit.
export const HERO_ACTIONS = ${JSON.stringify(actions)} as const;
export type HeroAction = keyof typeof HERO_ACTIONS;
// Game trait id -> asset id of its accessory layer.
export const TRAIT_ASSET: Record<string, string> = ${JSON.stringify(traits)};
// Existing accessory sheets, "<class>_<asset>_<action>" (Espinas has none for the knight).
export const ACCESSORY_SHEETS: ReadonlySet<string> = new Set(${JSON.stringify(accKeys)});
`);
